CREATE TABLE contractor (
    contractor_id SERIAL PRIMARY KEY,
    contractor_name VARCHAR(64) NOT NULL
);

-- ID:tä voidaan kysyä näillä kahdella funktiolla
-- SELECT currval(pg_get_serial_sequence('contractor', 'contractor_id'));

INSERT INTO contractor 
VALUES 
    (DEFAULT, 'Tmi Seppo Tärsky')
;

-- serial
-- https://www.postgresqltutorial.com/postgresql-serial/
-- vaatii defaultin käyttöä, jos asettaa käsin niin 
-- ID:n myöhempi rivi tulee asettumaan tämän päälle, eikä lisäys onnistu

/*
CREATE TABLE contractor2 (
    contractor2_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contractor_name VARCHAR(64) NOT NULL
);
*/

-- Identity
-- https://www.postgresqltutorial.com/postgresql-identity-column/
-- Tämä voisi olla parempi ratkaisu, mutta en saa toimimaan yliopiston koneella ollenkaan
-- voi johtua jostakin vanhasta psql versiosta tai muusta, mutta ei välttämättä ajankäytöllisesti
-- järkevää selvittää

-- DROP TABLE contractor;
