-- poistetaan viewit
DROP VIEW vw_tools;
DROP VIEW vw_hours;
DROP VIEW vw_bills;

-- poistetaan taulut
DROP TABLE Payment;
DROP TABLE Sold_tool;
DROP TABLE Billable_hour;
DROP TABLE Bill;
DROP TABLE Work_type;
DROP TABLE Tool;
DROP TABLE Vat_type;
DROP TABLE Bill_type;
DROP TABLE Bill_status;
DROP TABLE Contract;
DROP TABLE Contract_type;
DROP TABLE Project;
DROP TABLE Tax_credit_for_household;
DROP TABLE Customer;
DROP TABLE Contractor;
